apiVersion: v2
name: alloy
description: Grafana Alloy
type: application
version: 1.5.0
appVersion: 1.14.0
icon: >-
  https://raw.githubusercontent.com/grafana/alloy/main/docs/sources/assets/alloy_icon_orange.svg
dependencies:
  - name: crds
    version: 0.0.0
    condition: crds.create
